### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mahxxd** [LongCTygo/sot-piston-puzzle#3]
hey so i am making a mcc recreation and i have no idea how it works so if u can help me contact me on discord 
Matic Mahx#9461
plsss

**Comment by LongCTygo** [comment]
Hey, gladly to help. I can't seem to find your username on Discord, so would you mind contacting the other way? Mine is LongCT_#8874.

Also, just a heads-up, this is a solver program. All it does is that it solves the Sands of Times piston puzzle. I'm unsure if that's what you're looking for if you're looking to recreate MCC, but feel free to ask anything otherwise.

**Comment by LongCTygo** [comment]
> hey so i am making a mcc recreation and i have no idea how it works so if u can help me contact me on discord Matic Mahx#9461 plsss

Hey, gladly to help. I can't seem to find your username on Discord, so would you mind contacting the other way? Mine is LongCT_#8874.

Also, just a heads-up, this is a solver program. All it does is that it solves the Sands of Times piston puzzle. I'm unsure if that's what you're looking for if you're looking to recreate MCC, but feel free to ask anything otherwise.

**Comment by LongCTygo** [comment]
> hey so i am making a mcc recreation and i have no idea how it works so if u can help me contact me on discord Matic Mahx#9461 plsss

Found your account on the MCC Discord, reply to my message please.

Closed for "not an issue".
